### ISSUE TITLE
Error using "ranger" as fitting function...

### ISSUE THREAD

**Issue by coforfe** [Techtonique/ahead#1]
Hello,

I have just found this package and I am very surprised how easy is to define a fitting model with another ML algorithm and also another important aspect is that it is very intergrated with `forecast`. Thanks for all of this!.

The issue is that I have just played around with another alternative for the fitting algorithm, like `ranger`. Although it should offer an equivalent result to `randomForest`, I just wanted to try it:

```r
dynrmf(USAccDeaths, h=20, level=95, fit_func = ranger::ranger,
            fit_params = list(num.trees = 50), predict_func = predict)
```
but I get this error:

```r
> dynrmf(USAccDeaths, h=20, level=95, fit_func = ranger::ranger,
+             fit_params = list(num.trees = 50), predict_func = predict)
Error in (function (formula = NULL, data = NULL, num.trees = 500, mtry = NULL,  : 
  Error: No covariates found.
```

I am in the process of checking `dynrm.R` to see if I could find what I am doing wrongly.

Thanks!
Carlos.

**Comment by thierrymoudiki** [comment]
Hi Carlos,

Thanks for reaching out. Do not hesitate to star the repo if you like it :) `ranger` [is much faster](https://www.jstatsoft.org/article/view/v077i01) than `randomForest`, maybe that's the reason why you tried it out!

**Why it doesn't work with `ranger` so far?**

- to the best of my knowledge, and contrary to `randomForest`, `ranger` only has formula interface (that is, something like `fitting_func(y ~ ., data=df)`). I should mention in the docs that the fitting function must be implemented as `fitting_func(x, y)` (see for example the code for `ahead::ridge` and `predict`). 
- `ranger`'s `predict` function returns a list (containing an element `$predictions`)

**What do I suggest?**

I suggest to try to create two functions: one for fitting, the other for prediction
- The fitting function, must have a prototype like `fitting_func(x, y)`, and call `ranger::ranger` in its body. `ranger::ranger`'s argument `data` should be a data frame containing `y` and `x`. An object callable by `ranger`'s  `predict` is returned.
- The function `predict` should call `ranger`'s `predict` in its body, and return only `$predictions` instead of a list.
- Use your newly created functions with `ahead::dynrmf`

Let me know if anything is unclear.

**Comment by coforfe** [comment]
Hi Thierry,

Thanks for your clarifications.

OK, now I understand that for the fitting functions, it is needed to use an `x` and `y` interface. Or to create these functions to adapt both the _fitting_ process and the _predictions_.

Yes, my main idea to use `ranger` is for its speed, but also for the other additional parameters that `randomForest` does not have. I was doubtful about the `x`, `y` interface for `ranger` and it is supported. You can check that with this example:

```r
library(poorman)
library(ranger)
x <- iris %>% select(-Species)
y <- iris %>% select(Species) %>% pull(Species) %>% as.factor()
fit_iris <- ranger( x = x, y = y, data = iris, importance = "impurity")
``` 
The only missing piece of info that I do not fully follow is that for the function you propose `fitting_func(x, y)`:

- For the univariate case: what I should pass from my time series are the dates (`x`) and the time series values (`y`) ?.
- And for the multivariate case: well, that would be an extension of the univariate and the `x` would be all the covariates.

I will check, `ahead::ridge` to see this. By solving this, your package open many new modeling opportunities for time serie, to me easier to use than other approaches like `modeltime`, `forecastML`.

Thanks again for your prompt response. 
I already starred your repo.

**Comment by thierrymoudiki** [comment]
Hi @coforfe,

Could you please try this, and tell me if it works? 

I'll write a blog post about this. Maybe other people have the same question.

```r
fit_func <- function(x, y, ...)
{
  df <- data.frame(y=y, x) # naming of columns is mandatory for `predict`
  ranger::ranger(y ~ ., data=df, ...)
}

predict_func <- function(obj, newx)
{
  colnames(newx) <- paste0("X", 1:ncol(newx)) # mandatory, linked to df in fit_func
  predict(object=obj, data=newx)$predictions # only accepts a named newx
}

ahead::dynrmf(fdeaths, h=15, level=95, fit_func = fit_func,
              fit_params = list(num.trees = 500),
              predict_func = predict_func)
```

**Comment by coforfe** [comment]
Hi @thierrymoudiki ,

Yes, it worked flawlessly!.

```r
> fit_func <- function(x, y, ...)
+ {
+   df <- data.frame(y=y, x) # naming of columns is mandatory for `predict`
+   ranger::ranger(y ~ ., data=df, ...)
+ }
> 
> predict_func <- function(obj, newx)
+ {
+   colnames(newx) <- paste0("X", 1:ncol(newx)) # mandatory, linked to df in fit_func
+   predict(object=obj, data=newx)$predictions # only accepts a named newx
+ }
> 
> ahead::dynrmf(fdeaths, h=15, level=95, fit_func = fit_func,
+               fit_params = list(num.trees = 500),
+               predict_func = predict_func)
         Point Forecast    Lo 95    Hi 95
Jan 1980       742.6198 648.8185 836.4212
Feb 1980       806.8222 713.0208 900.6236
Mar 1980       784.2526 690.4512 878.0540
Apr 1980       660.7843 566.9829 754.5857
May 1980       521.3024 427.5011 615.1038
Jun 1980       440.1365 346.3351 533.9379
Jul 1980       438.9600 345.1586 532.7613
Aug 1980       413.4646 319.6632 507.2660
Sep 1980       398.6754 304.8741 492.4768
Oct 1980       400.7124 306.9110 494.5137
Nov 1980       438.0596 344.2583 531.8610
Dec 1980       511.1153 417.3140 604.9167
Jan 1981       681.0568 587.2554 774.8581
Feb 1981       800.4768 706.6755 894.2782
Mar 1981       813.6373 719.8359 907.4386
```
Thanks a lot for this!.
Carlos.

**Comment by thierrymoudiki** [comment]
Cool!
